apiVersion: v1
kind: Service
metadata:
  name: hsbc-transaction-service
spec:
  type: NodePort
  selector:
    app: hsbc-transaction-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
